<script lang="ts">
  import { MainPage } from 'kitbook'
  import type { PageData } from './$types'

  export let data: PageData
</script>

<MainPage {data} />

<!-- kitbook route files auto-generated by kitbook@1.0.0-alpha.50^ - do not edit as they will be overwritten next time kitbook updates routing -->
