name: 🐞 Bug report
description: Report an issue with Kitbook
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Double-Check
      description: Before submitting the issue, please make sure you have done the following
      options:
        - label: Read the entire [Kitbook docs](https://kitbook.vercel.app).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/jacob-8/kitbook/issues) that reports the same bug to avoid creating a duplicate.
          required: true
  - type: input
    id: version
    attributes:
      label: Kitbook version
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Do you intend to submit a PR for this issue?
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a [StackBlitz of the Kitbook Template](https://stackblitz.com/fork/github/jacob-8/kitbook/tree/main/packages/template) or a github repo that can reproduce the problem you ran into. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      placeholder: System, Browsers, Framework
    validations:
      required: false
