name: Greet

on:
  push:
    branches:
      - '**'

jobs:
  greet:
    steps:
      - uses: actions/checkout@v3

      - uses: ./packages/visual-regression-action
        id: hello
        with:
          who-to-greet: Jacob

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
