name: Svelte Check, & Unit Test Push

on:
  push:
    branches:
      - '**'

jobs:
  unit_test:
    name: Svelte Check & Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.6.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install

      - run: pnpm build:deps

      - run: pnpm -F kitbook sync
      - run: pnpm check

      - name: Run Vitest Unit Tests
        run: pnpm test

      # - name: Slack E2E Results Notification
      #   uses: 8398a7/action-slack@v3 # https://action-slack.netlify.app/
      #   if: failure()
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   with:
      #     status: ${{ job.status }}
      #     fields: workflow,repo,message,commit,author,action,ref # selectable (default: repo,message)
